services:
  db:
    image: 'mysql:8.3.0'
    environment:
      - 'MYSQL_DATABASE=scheduling_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    networks:
      - flow-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/scheduling_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flow-network

volumes:
  my-db:

networks:
  flow-network:

