services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=scheduling_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
