services:
  phpadmin:
    image: 'phpmyadmin:latest'
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: secret
    ports:
      - '5678:80'
    networks:
      - flow-network

  db:
    image: 'mysql:8.3.0'
    environment:
      - 'MYSQL_DATABASE=scheduling_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    networks:
      - flow-network
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  my-db:

networks:
  flow-network: